version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myAdmin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: transactionsDB
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/config/.env
    environment:
      POSTGRES_HOST: db
      DB_PORT: 5432
      DB_NAME: transactionsDB
      DB_USER: myAdmin
      DB_PASSWORD: mysecretpassword
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:

